remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ⚔ FX. Adi Lima | Home | Dokumentasi dan Cerita Silat
description: Membangun dokumentasi proyek dan menampilkannya sebagai GitHub Pages, menggunakan tema cerita silat.
keywords: cersil, cerita-silat, wuxia, dokumentasi, documentations, website, javascript, typescript, html
